export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  DIRECTION = 'ROLE_DIRECTION',
  CP = 'ROLE_CP',
  SOUTIENT = 'ROLE_SOUTIENT',
  SAAQ = 'ROLE_SAAQ',
  REPARTITION = 'ROLE_REPARTITION',
  HOTEL = 'ROLE_HOTEL',
  ENSEIGNANT = 'ROLE_ENSEIGNANT',
  ENTREPRISE = 'ROLE_ENTREPRISE',
}
